#### general settings
name: levin_dense
use_tb_logger: true
model: video_base
distortion: deblur
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: levin
    mode: levin
    interval_list: [1]
    HQ_pattern: ../datasets/levin_kernel_07_dense/sharp/**/*.png
    LQ_pattern: ../datasets/levin_kernel_07_dense/blur/**/*.png
    cache_keys: ~

    N_frames: 1
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    HQ_size: &HQ_SIZE 256
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  nf: 64
  front_RBs: 10
  back_RBs: 20
  N_frames: 1
  input_nc: 1
  kernel_dim: 512
  sphere_prior: false
  img_size: *HQ_SIZE
  BlurEstimator:
    norm: none
    use_sharp: true
    n_blocks: 4
    padding_type: reflect
    use_dropout: false
  VAE:
    get_norm_layer: none
    use_dropout: false

#### path
path:
  pretrain_model_G: ~
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-8

  pixel_criterion: cb
  pixel_weight: 1.0
  kernel_weight: 0.1
  gradient_loss_weight: 0.3
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 5e3
